Stop-Process -Name "AutoHotkey64" -ErrorAction SilentlyContinue
Start-Sleep -Seconds 1

$installDir = "$env:LOCALAPPDATA\SpaceToggleOS"
if (!(Test-Path $installDir)) { New-Item -ItemType Directory -Force -Path $installDir | Out-Null }
$ahkExe = "$installDir\AutoHotkey64.exe"
$ahkScript = "$installDir\SpaceToggleV9.ahk"

if (!(Test-Path $ahkExe)) {
    Write-Host "📦 Downloading AutoHotkey v2 Engine..." -ForegroundColor Yellow
    $zipFile = "$installDir\ahk.zip"
    Invoke-WebRequest -Uri "https://github.com/AutoHotkey/AutoHotkey/releases/download/v2.0.18/AutoHotkey_2.0.18.zip" -OutFile $zipFile
    Expand-Archive -Path $zipFile -DestinationPath $installDir -Force
    Remove-Item -Path $zipFile -Force
}

$ahkLines = @(
    '#Requires AutoHotkey v2.0',
    'SetTitleMatchMode 2',
    '#SingleInstance Force',
    '',
    'if !A_IsAdmin {',
    '    try {',
    '        Run(''*RunAs "'' A_ScriptFullPath ''"'')',
    '        ExitApp()',
    '    }',
    '}',
    '',
    'global ProfileList := ["Founders", "Gamers", "Professionals"]',
    'global CurrentProfileIndex := 1',
    'global TargetTrans := 255',
    'global PiPState := 0',
    'global SavedX := 0, SavedY := 0, SavedW := 0, SavedH := 0, SavedStyle := 0',
    'global HotkeyPressed := false',
    '',
    'ShowHUD(Message) {',
    '    ToolTip(Message, A_ScreenWidth // 2 - 100, A_ScreenHeight - 150)',
    '    SetTimer(() => ToolTip(), -2500)',
    '}',
    '',
    'SmartLaunch(exeTarget, runCommand, webFallback := "") {',
    '    if WinExist("ahk_exe " exeTarget) {',
    '        if WinActive("ahk_exe " exeTarget) {',
    '            WinMinimize("ahk_exe " exeTarget)',
    '        } else {',
    '            WinActivate("ahk_exe " exeTarget)',
    '        }',
    '    } else {',
    '        try {',
    '            Run(runCommand)',
    '        } catch {',
    '            if (webFallback != "") {',
    '                Run(webFallback)',
    '            }',
    '        }',
    '    }',
    '}',
    '',
    'OpenInBrowser(url) {',
    '    if WinExist("ahk_exe brave.exe") {',
    '        WinActivate("ahk_exe brave.exe")',
    '        Run(url)',
    '    } else if WinExist("ahk_exe chrome.exe") {',
    '        WinActivate("ahk_exe chrome.exe")',
    '        Run(url)',
    '    } else {',
    '        Run(url)',
    '    }',
    '}',
    '',
    '#HotIf HookSpace()',
    'HookSpace() => GetKeyState("Space", "P")',
    '',
    'RAlt:: {',
    '    global CurrentProfileIndex, ProfileList, HotkeyPressed',
    '    HotkeyPressed := true',
    '    CurrentProfileIndex := (CurrentProfileIndex == 3) ? 1 : CurrentProfileIndex + 1',
    '    ShowHUD("Workspace Active: [" ProfileList[CurrentProfileIndex] "]")',
    '}',
    '',
    'Esc:: {',
    '    global HotkeyPressed',
    '    HotkeyPressed := true',
    '    WinMinimizeAll()',
    '    ShowHUD("Workspace Secured")',
    '}',
    '',
    '$SC029:: {',
    '    global PiPState, SavedX, SavedY, SavedW, SavedH, SavedStyle, HotkeyPressed',
    '    HotkeyPressed := true',
    '    hwnd := WinExist("A")',
    '    if !hwnd',
    '        return',
    '',
    '    if (PiPState == 0) {',
    '        WinGetPos(&SavedX, &SavedY, &SavedW, &SavedH, hwnd)',
    '        SavedStyle := WinGetStyle(hwnd)',
    '        WinSetStyle("-0xC00000", hwnd)',
    '        WinSetAlwaysOnTop(1, hwnd)',
    '        WinMove(A_ScreenWidth - 420, 20, 400, 250, hwnd)',
    '        PiPState := 1',
    '    } else if (PiPState == 1) {',
    '        WinMove(20, 20, 400, 250, hwnd)',
    '        PiPState := 2',
    '    } else if (PiPState == 2) {',
    '        WinMove(20, A_ScreenHeight - 300, 400, 250, hwnd)',
    '        PiPState := 3',
    '    } else {',
    '        WinSetStyle(SavedStyle, hwnd)',
    '        WinSetAlwaysOnTop(0, hwnd)',
    '        WinMove(SavedX, SavedY, SavedW, SavedH, hwnd)',
    '        PiPState := 0',
    '    }',
    '}',
    '',
    '$,:: {',
    '    global HotkeyPressed',
    '    HotkeyPressed := true',
    '    if (WinActive("ahk_exe chrome.exe") || WinActive("ahk_exe brave.exe")) {',
    '        Send("^l")',
    '    } else if WinActive("ahk_exe discord.exe") {',
    '        Send("^k")',
    '    } else {',
    '        Send("{Tab}")',
    '    }',
    '}',
    '',
    '$WheelUp:: {',
    '    global TargetTrans, HotkeyPressed',
    '    HotkeyPressed := true',
    '    TargetTrans := Min(TargetTrans + 15, 255)',
    '    WinSetTransparent(TargetTrans, "A")',
    '}',
    '$WheelDown:: {',
    '    global TargetTrans, HotkeyPressed',
    '    HotkeyPressed := true',
    '    TargetTrans := Max(TargetTrans - 15, 40)',
    '    WinSetTransparent(TargetTrans, "A")',
    '}',
    '',
    '$a:: {',
    '    global HotkeyPressed',
    '    HotkeyPressed := true',
    '    if (ProfileList[CurrentProfileIndex] == "Founders") {',
    '        OpenInBrowser("https://gemini.google.com")',
    '    } else if (ProfileList[CurrentProfileIndex] == "Gamers") {',
    '        SmartLaunch("RadeonSoftware.exe", "RadeonSoftware.exe", "https://gemini.google.com")',
    '    } else {',
    '        SmartLaunch("photoshop.exe", "photoshop.exe")',
    '    }',
    '}',
    '$b:: {',
    '    global HotkeyPressed',
    '    HotkeyPressed := true',
    '    SmartLaunch("brave.exe", "brave.exe", "https://www.google.com")',
    '}',
    '$c:: {',
    '    global HotkeyPressed',
    '    HotkeyPressed := true',
    '    if (ProfileList[CurrentProfileIndex] == "Founders") {',
    '        SmartLaunch("chrome.exe", "chrome.exe")',
    '    } else if (ProfileList[CurrentProfileIndex] == "Gamers") {',
    '        SmartLaunch("cs2.exe", "steam://rungameid/730")',
    '    } else {',
    '        SmartLaunch("canva.exe", "canva.exe", "https://www.canva.com")',
    '    }',
    '}',
    '$d:: {',
    '    global HotkeyPressed',
    '    HotkeyPressed := true',
    '    if (ProfileList[CurrentProfileIndex] == "Professionals") {',
    '        SmartLaunch("resolve.exe", "resolve.exe")',
    '    } else {',
    '        SmartLaunch("discord.exe", EnvGet("LOCALAPPDATA") . "\Discord\Update.exe --processStart Discord.exe")',
    '    }',
    '}',
    '$e:: {',
    '    global HotkeyPressed',
    '    HotkeyPressed := true',
    '    if (ProfileList[CurrentProfileIndex] == "Founders") {',
    '        OpenInBrowser("https://sheets.google.com")',
    '    } else if (ProfileList[CurrentProfileIndex] == "Gamers") {',
    '        SmartLaunch("EpicGamesLauncher.exe", "EpicGamesLauncher.exe")',
    '    } else {',
    '        SmartLaunch("excel.exe", "excel.exe")',
    '    }',
    '}',
    '$f:: {',
    '    global HotkeyPressed',
    '    HotkeyPressed := true',
    '    SmartLaunch("explorer.exe", "explorer.exe")',
    '}',
    '$g:: {',
    '    global HotkeyPressed',
    '    HotkeyPressed := true',
    '    if (ProfileList[CurrentProfileIndex] == "Founders") {',
    '        OpenInBrowser("https://mail.google.com")',
    '    } else if (ProfileList[CurrentProfileIndex] == "Gamers") {',
    '        SmartLaunch("NVIDIA GeForce Experience.exe", "NVIDIA GeForce Experience.exe")',
    '    } else {',
    '        OpenInBrowser("https://github.com")',
    '    }',
    '}',
    '$h:: {',
    '    global HotkeyPressed',
    '    HotkeyPressed := true',
    '    OpenInBrowser("https://github.com")',
    '}',
    '$i:: {',
    '    global HotkeyPressed',
    '    HotkeyPressed := true',
    '    if (ProfileList[CurrentProfileIndex] == "Founders") {',
    '        OpenInBrowser("https://www.instagram.com")',
    '    } else if (ProfileList[CurrentProfileIndex] == "Gamers") {',
    '        SmartLaunch("itch.exe", EnvGet("LOCALAPPDATA") . "\itch\itch.exe")',
    '    } else {',
    '        SmartLaunch("illustrator.exe", "illustrator.exe")',
    '    }',
    '}',
    '$j:: {',
    '    global HotkeyPressed',
    '    HotkeyPressed := true',
    '    if (ProfileList[CurrentProfileIndex] == "Professionals") {',
    '        SmartLaunch("idea64.exe", "idea64.exe")',
    '    } else {',
    '        OpenInBrowser("https://docs.google.com")',
    '    }',
    '}',
    '$k:: {',
    '    global HotkeyPressed',
    '    HotkeyPressed := true',
    '    OpenInBrowser("https://calendar.google.com")',
    '}',
    '$l:: {',
    '    global HotkeyPressed',
    '    HotkeyPressed := true',
    '    if (ProfileList[CurrentProfileIndex] == "Gamers") {',
    '        SmartLaunch("LeagueClient.exe", "LeagueClient.exe")',
    '    } else {',
    '        OpenInBrowser("https://www.linkedin.com")',
    '    }',
    '}',
    '$m:: {',
    '    global HotkeyPressed',
    '    HotkeyPressed := true',
    '    if (ProfileList[CurrentProfileIndex] == "Gamers") {',
    '        SmartLaunch("MSIAfterburner.exe", "MSIAfterburner.exe")',
    '    } else {',
    '        OpenInBrowser("https://cinemaos.live/")',
    '    }',
    '}',
    '$n:: {',
    '    global HotkeyPressed',
    '    HotkeyPressed := true',
    '    if (ProfileList[CurrentProfileIndex] == "Gamers") {',
    '        SmartLaunch("NVIDIA App.exe", "NVIDIA App.exe")',
    '    } else if (ProfileList[CurrentProfileIndex] == "Professionals") {',
    '        SmartLaunch("notion.exe", "notion.exe", "https://www.notion.so")',
    '    } else {',
    '        OpenInBrowser("https://keep.google.com")',
    '    }',
    '}',
    '$o:: {',
    '    global HotkeyPressed',
    '    HotkeyPressed := true',
    '    if (ProfileList[CurrentProfileIndex] == "Gamers") {',
    '        SmartLaunch("obs64.exe", "obs64.exe")',
    '    } else if (ProfileList[CurrentProfileIndex] == "Professionals") {',
    '        SmartLaunch("outlook.exe", "outlook.exe")',
    '    } else {',
    '        OpenInBrowser("https://drive.google.com")',
    '    }',
    '}',
    '$p:: {',
    '    global HotkeyPressed',
    '    HotkeyPressed := true',
    '    if (ProfileList[CurrentProfileIndex] == "Gamers") {',
    '        SmartLaunch("TslGame.exe", "steam://rungameid/578080")',
    '    } else if (ProfileList[CurrentProfileIndex] == "Professionals") {',
    '        SmartLaunch("powerpnt.exe", "powerpnt.exe")',
    '    } else {',
    '        OpenInBrowser("https://photos.google.com")',
    '    }',
    '}',
    '$q:: {',
    '    global HotkeyPressed',
    '    HotkeyPressed := true',
    '    OpenInBrowser("https://notebooklm.google")',
    '}',
    '$r:: {',
    '    global HotkeyPressed',
    '    HotkeyPressed := true',
    '    OpenInBrowser("https://www.reddit.com")',
    '}',
    '$s:: {',
    '    global HotkeyPressed',
    '    HotkeyPressed := true',
    '    if (ProfileList[CurrentProfileIndex] == "Founders") {',
    '        SmartLaunch("spotify.exe", "spotify.exe", "https://open.spotify.com")',
    '    } else if (ProfileList[CurrentProfileIndex] == "Gamers") {',
    '        SmartLaunch("steam.exe", "steam.exe")',
    '    } else {',
    '        SmartLaunch("slack.exe", "slack.exe")',
    '    }',
    '}',
    '$t:: {',
    '    global HotkeyPressed',
    '    HotkeyPressed := true',
    '    if (ProfileList[CurrentProfileIndex] == "Founders") {',
    '        SmartLaunch("wt.exe", "wt.exe")',
    '    } else if (ProfileList[CurrentProfileIndex] == "Gamers") {',
    '        OpenInBrowser("https://twitch.tv")',
    '    } else {',
    '        SmartLaunch("telegram.exe", "telegram.exe")',
    '    }',
    '}',
    '$u:: {',
    '    global HotkeyPressed',
    '    HotkeyPressed := true',
    '    if (ProfileList[CurrentProfileIndex] == "Professionals") {',
    '        OpenInBrowser("https://drive.google.com")',
    '    } else {',
    '        SmartLaunch("uTorrent.exe", "uTorrent.exe")',
    '    }',
    '}',
    '$v:: {',
    '    global HotkeyPressed',
    '    HotkeyPressed := true',
    '    if (ProfileList[CurrentProfileIndex] == "Gamers") {',
    '        SmartLaunch("vlr.exe", "vlr.exe")',
    '    } else {',
    '        SmartLaunch("vlc.exe", "vlc.exe")',
    '    }',
    '}',
    '$w:: {',
    '    global HotkeyPressed',
    '    HotkeyPressed := true',
    '    if (ProfileList[CurrentProfileIndex] == "Professionals") {',
    '        OpenInBrowser("https://web.whatsapp.com")',
    '    } else {',
    '        SmartLaunch("WhatsApp.exe", "WhatsApp.exe", "https://web.whatsapp.com")',
    '    }',
    '}',
    '$x:: {',
    '    global HotkeyPressed',
    '    HotkeyPressed := true',
    '    if (ProfileList[CurrentProfileIndex] == "Gamers") {',
    '        SmartLaunch("XboxPcApp.exe", "XboxPcApp.exe")',
    '    } else {',
    '        OpenInBrowser("https://www.x.com")',
    '    }',
    '}',
    '$y:: {',
    '    global HotkeyPressed',
    '    HotkeyPressed := true',
    '    if (ProfileList[CurrentProfileIndex] == "Gamers") {',
    '        OpenInBrowser("https://gaming.youtube.com")',
    '    } else {',
    '        OpenInBrowser("https://www.youtube.com")',
    '    }',
    '}',
    '$z:: {',
    '    global HotkeyPressed',
    '    HotkeyPressed := true',
    '    SmartLaunch("zoom.exe", "zoom.exe")',
    '}',
    '',
    '#HotIf',
    '',
    '~Space Up:: {',
    '    global HotkeyPressed',
    '    if (!HotkeyPressed) {',
    '        Send("{Space}")',
    '    }',
    '    HotkeyPressed := false',
    '}'
)

$ahkLines | Out-File -FilePath $ahkScript -Encoding utf8 -Force

Write-Host "⚙️ Registering Window Manager Shortcut..." -ForegroundColor Yellow
$WshShell = New-Object -ComObject WScript.Shell
$StartupPath = "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Startup\SpaceToggleV9.lnk"
$Shortcut = $WshShell.CreateShortcut($StartupPath)
$Shortcut.TargetPath = $ahkExe
$Shortcut.Arguments = "`"$ahkScript`""
$Shortcut.WorkingDirectory = $installDir
$Shortcut.Save()

Write-Host "⚡ Starting SpaceToggle OS..." -ForegroundColor Green
Start-Process -FilePath $ahkExe -ArgumentList "`"$ahkScript`""
Write-Host "✅ Installation completed successfully!" -ForegroundColor Green
